In [3]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
#Cargar archivo csv
from google.colab import files
files.upload()

Saving microretailer_mit_lift_lab_actualizado.xlsx to microretailer_mit_lift_lab_actualizado.xlsx


{'microretailer_mit_lift_lab_actualizado.xlsx': b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00b\xee\x9dh^\x01\x00\x00\x90\x04\x00\x00\x13\x00\x08\x02[Content_Types].xml \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0

In [5]:
#Cargar desde un xlsx sin indice
Micro_Retailer=pd.read_excel('microretailer_mit_lift_lab_actualizado.xlsx')


In [6]:
#Identificar valores nulos
valores_nulos_Micro_Retailer=Micro_Retailer.isnull().sum()
valores_nulos_Micro_Retailer

_record_id                                0
_title                                    0
_server_updated_at                        0
_updated_by                               0
_geometry                                 0
                                       ... 
234_willingness_participate_workshop    125
318_shopkeeper_name                     249
319_shopkeepers_last_name               252
236_whatsapp                            255
235_email                               283
Length: 106, dtype: int64

In [7]:
#Reemplazamos valores nulos con el método más sencillo
data2_Micro_Retailer=Micro_Retailer.fillna(method='bfill')

#Reemplazamos valores nulos con el método más sencillo
data2_Micro_Retailer=data2_Micro_Retailer.fillna(method='ffill')
data2_Micro_Retailer

_record_id             _title  \
0    71326e5f-441e-4be7-bc68-b828973b8e3b  November 17, 2022   
1    a38b7c68-0afa-4419-a580-7086538b2e21  November 17, 2022   
2    c11ef540-e06c-4722-a071-09a127ebc23c  November 10, 2022   
3    c7434cb2-dde0-4901-80d7-3d60506ebd27  November 10, 2022   
4    3c2177cc-677b-4106-8ed2-6e50f7671a0e  November 17, 2022   
..                                    ...                ...   
325  efe2e285-c67e-4a07-8331-218bc4a7203d   November 3, 2022   
326  2413f06e-15cc-4a6f-8e83-5224c6824b12   November 3, 2022   
327  9ff658db-4dc5-48b6-aa0b-5c6668bb6720   November 3, 2022   
328  e88aa9c1-dc8b-4180-99a1-2e0118ad905d   November 3, 2022   
329  bf720ff0-3b7d-47ed-ba49-f5d4bfb7293c   November 3, 2022   

          _server_updated_at     _updated_by  \
0    2022-11-18 20:48:40 UTC   Uriel Bonilla   
1    2022-11-18 20:48:39 UTC   Uriel Bonilla   
2    2022-11-18 20:48:38 UTC   Uriel Bonilla   
3    2022-11-18 20:48:38 UTC   Uriel Bonilla   
4    2022-11-18 13:30:19 UTC   Fernando Báez   
..                       ...             ...   
325  2022-11-03 17:05:23 UTC  Francisco Adán   
326  2022-11-03 16:50:48 UTC    Emilio Garza   
327  2022-11-03 16:28:14 UTC    Emilio Garza   
328  2022-11-03 16:18:37 UTC  Francisco Adán   
329  2022-11-03 16:15:13 UTC    Emilio Garza   

                                         _geometry  _latitude  _longitude  \
0    SRID=4326;POINT(-98.2013790035 19.0439654034)  19.043965  -98.201379   
1    SRID=4326;POINT(-98.2016961782 19.0439749111)  19.043975  -98.201696   
2    SRID=4326;POINT(-98.1964474585 19.0432999683)  19.043300  -98.196447   
3     SRID=4326;POINT(-98.197072078 19.0405699102)  19.040570  -98.197072   
4     SRID=4326;POINT(-98.201134218 19.0436743967)  19.043674  -98.201134   
..                                             ...        ...         ...   
325         SRID=4326;POINT(-98.194174 19.0431876)  19.043188  -98.194174   
326  SRID=4326;POINT(-98.1940658722 19.0431145635)  19.043115  -98.194066   
327  SRID=4326;POINT(-98.1934387078 19.0428094171)  19.042809  -98.193439   
328          SRID=4326;POINT(-98.193818 19.042558)  19.042558  -98.193818   
329  SRID=4326;POINT(-98.1937349172 19.0428229892)  19.042823  -98.193735   

                                        228_store_name 229_store_picture  \
0                               Mini súper 7 hermanos            1 Photo   
1                                     Super papas Lulu           1 Photo   
2                                      Arte Paquistán            1 Photo   
3                                            El vestir           1 Photo   
4                                       Antojitos Tony           1 Photo   
..                                                 ...               ...   
325                                      Xuti Galería            1 Photo   
326                                         July Store           1 Photo   
327                                          La fonda            1 Photo   
328  Birria de Res "Hermanos Negreros 2" estilo Tij...           1 Photo   
329                          Restaurante el alfeñique            1 Photo   

                   232_type_of_store  ... 261_technology_organization  \
0     Grocery store (aka. nanostore)  ...                  De acuerdo   
1     Grocery store (aka. nanostore)  ...               En desacuerdo   
2     Grocery store (aka. nanostore)  ...               En desacuerdo   
3     Grocery store (aka. nanostore)  ...               En desacuerdo   
4    Micro-restaurant (aka. fondita)  ...       Totalmente de acuerdo   
..                               ...  ...                         ...   
325         productos tradicionales   ...    Totalmente en desacuerdo   
326   Grocery store (aka. nanostore)  ...    Totalmente en desacuerdo   
327  Micro-restaurant (aka. fondita)  ...    Totalmente en desacuerdo   
328  Micro-restaurant (aka. fondita)  ...    Totalmente en desacuerdo   
329  Micro-restaurant (aka. fondita)  ...   

In [8]:
#corroboramos valores nulos
valores_nulos=data2_Micro_Retailer.isnull().sum()
valores_nulos

_record_id                              0
_title                                  0
_server_updated_at                      0
_updated_by                             0
_geometry                               0
                                       ..
234_willingness_participate_workshop    0
318_shopkeeper_name                     0
319_shopkeepers_last_name               0
236_whatsapp                            0
235_email                               0
Length: 106, dtype: int64

In [9]:
#corroboramos valores nulos
valores_nulos=data2_Micro_Retailer.isnull().sum().sum()
valores_nulos

0

In [10]:
data2_Micro_Retailer.info(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 106 columns):
 #    Column                                                      Dtype  
---   ------                                                      -----  
 0    _record_id                                                  object 
 1    _title                                                      object 
 2    _server_updated_at                                          object 
 3    _updated_by                                                 object 
 4    _geometry                                                   object 
 5    _latitude                                                   float64
 6    _longitude                                                  float64
 7    228_store_name                                              object 
 8    229_store_picture                                           object 
 9    232_type_of_store                                           object 
 10   

In [11]:
#Filtro por columnas (Usamos solo las columnas de variables cuantitativas)
filtro_columnas_innecesarias=data2_Micro_Retailer.iloc[ : , [5,6,13,14,16,21,22,31,42,49,51,59,29,33,78,90]]
filtro_columnas_innecesarias

_latitude  _longitude  97_number_of_customers_in_store  \
0    19.043965  -98.201379                                1   
1    19.043975  -98.201696                                2   
2    19.043300  -98.196447                                2   
3    19.040570  -98.197072                                1   
4    19.043674  -98.201134                                3   
..         ...         ...                              ...   
325  19.043188  -98.194174                                0   
326  19.043115  -98.194066                                1   
327  19.042809  -98.193439                                3   
328  19.042558  -98.193818                                0   
329  19.042823  -98.193735                                1   

     268_number_fridges  104_how_many_shelves_does_the_micro_retailer_have  \
0                   3.0                                                  3   
1                   0.0                                                  0   
2                   0.0                                                  0   
3                   0.0                                                  0   
4                   2.0                                                  3   
..                  ...                                                ...   
325                 1.0                                                  7   
326                 0.0                                                  5   
327                 1.0                                                  1   
328                 1.0                                                  1   
329                 3.0                                                  1   

     2_current_permanent_employees  4_number_permanent_employees_last_year  \
0                              2.0                                    10.0   
1                              0.0                                     0.0   
2                              0.0                                     0.0   
3                              0.0                                     0.0   
4                             10.0                                    14.0   
..                             ...                                     ...   
325                            4.0                                     2.0   
326                            4.0                                     2.0   
327                            4.0                                     2.0   
328                            4.0                                     2.0   
329                            4.0                                     2.0   

     145_number_direct_competitors  272_card_days_receive_money  \
0                              5.0                          0.0   
1                             10.0                          0.0   
2                             10.0                          0.0   
3                             10.0                          0.0   
4                              3.0                          0.0   
..                             ...                          ...   
325                            5.0                          1.0   
326                            5.0                          1.0   
327                            5.0                          1.0   
328                            5.0                          1.0   
329                            5.0                          1.0   

     276_expected_days_informal_credit  36_credit_default_rate  \
0                                  1.0                     1.0   
1                                  1.0                     1.0   
2                                  1.0                     1.0   
3                                  1.0                     1.0   
4                                  1.0                     1.0   
..                                 ...                     ...   
325                                2.0                     0.0   
326                                2.0   

In [12]:
#Método aplicando cuartiles Encuentro cuartules de 0.25 y 0.75
y=filtro_columnas_innecesarias
percentile25=y.quantile(0.25) #Q1
percentile75=y.quantile(0.75) #Q3
iqr= percentile75 - percentile25

Limite_Superior_iqr= percentile75 + 1.5*iqr
Limite_Inferior_iqr= percentile25 - 1.5*iqr
print("Limite superior permitido", Limite_Superior_iqr)
print("Limite inferior permitido", Limite_Inferior_iqr)

Limite superior permitido _latitude                                            19.114494
_longitude                                          -98.103732
97_number_of_customers_in_store                       5.000000
268_number_fridges                                    5.000000
104_how_many_shelves_does_the_micro_retailer_have    13.500000
2_current_permanent_employees                         3.500000
4_number_permanent_employees_last_year                5.000000
145_number_direct_competitors                        11.375000
272_card_days_receive_money                           1.000000
276_expected_days_informal_credit                    36.000000
36_credit_default_rate                                5.000000
62_frequency_only_services                           17.500000
103_number_own_fridges                                5.000000
24_burnout                                            9.500000
172_supplier_frequency                               13.500000
163_number_high_perishable_pr

In [13]:
#Encontramos Outliers del dataframe 
outliers_iqr_Micro_retailer=y[(y>Limite_Superior_iqr)|(y<Limite_Inferior_iqr)]
outliers_iqr_Micro_retailer

_latitude  _longitude  97_number_of_customers_in_store  \
0          NaN         NaN                              NaN   
1          NaN         NaN                              NaN   
2          NaN         NaN                              NaN   
3          NaN         NaN                              NaN   
4          NaN         NaN                              NaN   
..         ...         ...                              ...   
325        NaN         NaN                              NaN   
326        NaN         NaN                              NaN   
327        NaN         NaN                              NaN   
328        NaN         NaN                              NaN   
329        NaN         NaN                              NaN   

     268_number_fridges  104_how_many_shelves_does_the_micro_retailer_have  \
0                   NaN                                                NaN   
1                   NaN                                                NaN   
2                   NaN                                                NaN   
3                   NaN                                                NaN   
4                   NaN                                                NaN   
..                  ...                                                ...   
325                 NaN                                                NaN   
326                 NaN                                                NaN   
327                 NaN                                                NaN   
328                 NaN                                                NaN   
329                 NaN                                                NaN   

     2_current_permanent_employees  4_number_permanent_employees_last_year  \
0                              NaN                                    10.0   
1                              NaN                                     NaN   
2                              NaN                                     NaN   
3                              NaN                                     NaN   
4                             10.0                                    14.0   
..                             ...                                     ...   
325                            4.0                                     NaN   
326                            4.0                                     NaN   
327                            4.0                                     NaN   
328                            4.0                                     NaN   
329                            4.0                                     NaN   

     145_number_direct_competitors  272_card_days_receive_money  \
0                              NaN                          0.0   
1                              NaN                          0.0   
2                              NaN                          0.0   
3                              NaN                          0.0   
4                              NaN                          0.0   
..                             ...                          ...   
325                            NaN                          NaN   
326                            NaN                          NaN   
327                            NaN                          NaN   
328                            NaN                          NaN   
329                            NaN                          NaN   

     276_expected_days_informal_credit  36_credit_default_rate  \
0                                  NaN                     NaN   
1                                  NaN                     NaN   
2                                  NaN                     NaN   
3                                  NaN                     NaN   
4                                  NaN                     NaN   
..                                 ...                     ...   
325                                NaN                     NaN   
326                                NaN   

In [14]:
#Obtenemos datos limpios del dataframe
data3_iqr_Micro_Retailer=y[(y<=Limite_Superior_iqr)&(y>=Limite_Inferior_iqr)]
data3_iqr_Micro_Retailer

_latitude  _longitude  97_number_of_customers_in_store  \
0    19.043965  -98.201379                              1.0   
1    19.043975  -98.201696                              2.0   
2    19.043300  -98.196447                              2.0   
3    19.040570  -98.197072                              1.0   
4    19.043674  -98.201134                              3.0   
..         ...         ...                              ...   
325  19.043188  -98.194174                              0.0   
326  19.043115  -98.194066                              1.0   
327  19.042809  -98.193439                              3.0   
328  19.042558  -98.193818                              0.0   
329  19.042823  -98.193735                              1.0   

     268_number_fridges  104_how_many_shelves_does_the_micro_retailer_have  \
0                   3.0                                                3.0   
1                   0.0                                                0.0   
2                   0.0                                                0.0   
3                   0.0                                                0.0   
4                   2.0                                                3.0   
..                  ...                                                ...   
325                 1.0                                                7.0   
326                 0.0                                                5.0   
327                 1.0                                                1.0   
328                 1.0                                                1.0   
329                 3.0                                                1.0   

     2_current_permanent_employees  4_number_permanent_employees_last_year  \
0                              2.0                                     NaN   
1                              0.0                                     0.0   
2                              0.0                                     0.0   
3                              0.0                                     0.0   
4                              NaN                                     NaN   
..                             ...                                     ...   
325                            NaN                                     2.0   
326                            NaN                                     2.0   
327                            NaN                                     2.0   
328                            NaN                                     2.0   
329                            NaN                                     2.0   

     145_number_direct_competitors  272_card_days_receive_money  \
0                              5.0                          NaN   
1                             10.0                          NaN   
2                             10.0                          NaN   
3                             10.0                          NaN   
4                              3.0                          NaN   
..                             ...                          ...   
325                            5.0                          1.0   
326                            5.0                          1.0   
327                            5.0                          1.0   
328                            5.0                          1.0   
329                            5.0                          1.0   

     276_expected_days_informal_credit  36_credit_default_rate  \
0                                  1.0                     1.0   
1                                  1.0                     1.0   
2                                  1.0                     1.0   
3                                  1.0                     1.0   
4                                  1.0                     1.0   
..                                 ...                     ...   
325                                2.0                     0.0   
326                                2.0   

In [15]:
#Obtenemos info de las columnas para corroborar que estemos ocupando los datos apropiados
data3_iqr_Micro_Retailer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Data columns (total 16 columns):
 #   Column                                             Non-Null Count  Dtype  
---  ------                                             --------------  -----  
 0   _latitude                                          330 non-null    float64
 1   _longitude                                         330 non-null    float64
 2   97_number_of_customers_in_store                    318 non-null    float64
 3   268_number_fridges                                 313 non-null    float64
 4   104_how_many_shelves_does_the_micro_retailer_have  308 non-null    float64
 5   2_current_permanent_employees                      284 non-null    float64
 6   4_number_permanent_employees_last_year             311 non-null    float64
 7   145_number_direct_competitors                      314 non-null    float64
 8   272_card_days_receive_money                        215 non-null    float64
 9   276_expect

In [16]:
#corroboramos valores nulos
valores_nulos=y.isnull().sum()
valores_nulos

_latitude                                            0
_longitude                                           0
97_number_of_customers_in_store                      0
268_number_fridges                                   0
104_how_many_shelves_does_the_micro_retailer_have    0
2_current_permanent_employees                        0
4_number_permanent_employees_last_year               0
145_number_direct_competitors                        0
272_card_days_receive_money                          0
276_expected_days_informal_credit                    0
36_credit_default_rate                               0
62_frequency_only_services                           0
103_number_own_fridges                               0
24_burnout                                           0
172_supplier_frequency                               0
163_number_high_perishable_products                  0
dtype: int64

In [17]:
#Reemplazamos valores atípicos (nulos) del dataframe con "mean"
#Realizamos una copia del dataframe
data4_iqr=y.copy()
data4_iqr=y.fillna(round(data4_iqr.mean(),1))
data4_iqr

_latitude  _longitude  97_number_of_customers_in_store  \
0    19.043965  -98.201379                                1   
1    19.043975  -98.201696                                2   
2    19.043300  -98.196447                                2   
3    19.040570  -98.197072                                1   
4    19.043674  -98.201134                                3   
..         ...         ...                              ...   
325  19.043188  -98.194174                                0   
326  19.043115  -98.194066                                1   
327  19.042809  -98.193439                                3   
328  19.042558  -98.193818                                0   
329  19.042823  -98.193735                                1   

     268_number_fridges  104_how_many_shelves_does_the_micro_retailer_have  \
0                   3.0                                                  3   
1                   0.0                                                  0   
2                   0.0                                                  0   
3                   0.0                                                  0   
4                   2.0                                                  3   
..                  ...                                                ...   
325                 1.0                                                  7   
326                 0.0                                                  5   
327                 1.0                                                  1   
328                 1.0                                                  1   
329                 3.0                                                  1   

     2_current_permanent_employees  4_number_permanent_employees_last_year  \
0                              2.0                                    10.0   
1                              0.0                                     0.0   
2                              0.0                                     0.0   
3                              0.0                                     0.0   
4                             10.0                                    14.0   
..                             ...                                     ...   
325                            4.0                                     2.0   
326                            4.0                                     2.0   
327                            4.0                                     2.0   
328                            4.0                                     2.0   
329                            4.0                                     2.0   

     145_number_direct_competitors  272_card_days_receive_money  \
0                              5.0                          0.0   
1                             10.0                          0.0   
2                             10.0                          0.0   
3                             10.0                          0.0   
4                              3.0                          0.0   
..                             ...                          ...   
325                            5.0                          1.0   
326                            5.0                          1.0   
327                            5.0                          1.0   
328                            5.0                          1.0   
329                            5.0                          1.0   

     276_expected_days_informal_credit  36_credit_default_rate  \
0                                  1.0                     1.0   
1                                  1.0                     1.0   
2                                  1.0                     1.0   
3                                  1.0                     1.0   
4                                  1.0                     1.0   
..                                 ...                     ...   
325                                2.0                     0.0   
326                                2.0   

In [18]:
#Observamos variables dentro del dataframe
data4_iqr

_latitude  _longitude  97_number_of_customers_in_store  \
0    19.043965  -98.201379                                1   
1    19.043975  -98.201696                                2   
2    19.043300  -98.196447                                2   
3    19.040570  -98.197072                                1   
4    19.043674  -98.201134                                3   
..         ...         ...                              ...   
325  19.043188  -98.194174                                0   
326  19.043115  -98.194066                                1   
327  19.042809  -98.193439                                3   
328  19.042558  -98.193818                                0   
329  19.042823  -98.193735                                1   

     268_number_fridges  104_how_many_shelves_does_the_micro_retailer_have  \
0                   3.0                                                  3   
1                   0.0                                                  0   
2                   0.0                                                  0   
3                   0.0                                                  0   
4                   2.0                                                  3   
..                  ...                                                ...   
325                 1.0                                                  7   
326                 0.0                                                  5   
327                 1.0                                                  1   
328                 1.0                                                  1   
329                 3.0                                                  1   

     2_current_permanent_employees  4_number_permanent_employees_last_year  \
0                              2.0                                    10.0   
1                              0.0                                     0.0   
2                              0.0                                     0.0   
3                              0.0                                     0.0   
4                             10.0                                    14.0   
..                             ...                                     ...   
325                            4.0                                     2.0   
326                            4.0                                     2.0   
327                            4.0                                     2.0   
328                            4.0                                     2.0   
329                            4.0                                     2.0   

     145_number_direct_competitors  272_card_days_receive_money  \
0                              5.0                          0.0   
1                             10.0                          0.0   
2                             10.0                          0.0   
3                             10.0                          0.0   
4                              3.0                          0.0   
..                             ...                          ...   
325                            5.0                          1.0   
326                            5.0                          1.0   
327                            5.0                          1.0   
328                            5.0                          1.0   
329                            5.0                          1.0   

     276_expected_days_informal_credit  36_credit_default_rate  \
0                                  1.0                     1.0   
1                                  1.0                     1.0   
2                                  1.0                     1.0   
3                                  1.0                     1.0   
4                                  1.0                     1.0   
..                                 ...                     ...   
325                                2.0                     0.0   
326                                2.0   

In [19]:
#analizamos caso 1 de correlación entre variable de número de clientes en la tienda respecto al número de estantes en la tienda, el número de refrigeradores y el número de empleados permanentes
Vars_Indep= data4_iqr[['268_number_fridges','104_how_many_shelves_does_the_micro_retailer_have', '2_current_permanent_employees']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

In [20]:
#se define modelo como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [21]:
#Verificamos la función relacionada al modelo 
type(model)

sklearn.linear_model._base.LinearRegression

In [22]:
#ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)

LinearRegression()

In [23]:
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'normalize': 'deprecated',
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['268_number_fridges',
        '104_how_many_shelves_does_the_micro_retailer_have',
        '2_current_permanent_employees'], dtype=object),
 'n_features_in_': 3,
 'coef_': array([0.19590676, 0.0080384 , 0.08928311]),
 '_residues': 972.3842620033486,
 'rank_': 3,
 'singular_': array([260.78872511,  58.823247  ,  42.76081943]),
 'intercept_': 0.8414396869333318}

In [24]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R determinado
model.score(Vars_Indep,Var_Dep)

0.1130725423688903

In [25]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep= data4_iqr[['268_number_fridges','104_how_many_shelves_does_the_micro_retailer_have', '2_current_permanent_employees']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

In [26]:
#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

In [27]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [28]:
#Se escalan todos los datos
escalar= StandardScaler()

In [29]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [30]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [31]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [32]:
#Realizamos una predicción
y_pred= algoritmo.predict(X_test)
y_pred 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[45  1  0  0  0  0  0  0  0]
 [16  0  1  0  0  0  0  0  0]
 [16  0  2  2  0  0  0  0  0]
 [ 8  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0]]


In [34]:
#Calculo la precisión del modelo 
from sklearn.metrics import precision_score
precision= precision_score(y_test, y_pred, average="micro", pos_label="yes")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.47474747474747475


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,


In [35]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud= accuracy_score(y_test, y_pred)
print('Exactitud del modelo')
print(exactitud)

Exactitud del modelo
0.47474747474747475


In [36]:
#Calculo la sensibilidad del modelo 
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test, y_pred, average='micro', pos_label="yes")
print('Sensibilidad del modelo')
print(sensibilidad)

Sensibilidad del modelo
0.47474747474747475


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,


# Conjunto de variables 2

In [37]:
#3y4
#analizamos caso 1 de correlación entre variable de número de clientes en la tienda respecto al número de estantes en la tienda, el número de refrigeradores y el número de empleados permanentes
Vars_Indep= data4_iqr[['145_number_direct_competitors','272_card_days_receive_money', '4_number_permanent_employees_last_year']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

In [38]:
#se define modelo como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [39]:
#Verificamos la función relacionada al modelo 
type(model)

sklearn.linear_model._base.LinearRegression

In [41]:
#ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)

LinearRegression()

In [42]:
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'normalize': 'deprecated',
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['145_number_direct_competitors', '272_card_days_receive_money',
        '4_number_permanent_employees_last_year'], dtype=object),
 'n_features_in_': 3,
 'coef_': array([-0.00533727,  0.00910135,  0.07015527]),
 '_residues': 1064.029636800752,
 'rank_': 3,
 'singular_': array([81.80139886, 76.41805793, 13.55424753]),
 'intercept_': 1.2471934335937875}

In [43]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R determinado
model.score(Vars_Indep,Var_Dep)

0.029481309510751674

In [44]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep= data4_iqr[['145_number_direct_competitors','272_card_days_receive_money', '4_number_permanent_employees_last_year']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

In [45]:
#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

In [46]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [47]:
#Se escalan todos los datos
escalar= StandardScaler()

In [48]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [49]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [50]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [51]:
#Realizamos una predicción
y_pred= algoritmo.predict(X_test)
y_pred 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[36  0  1  0  0  0  0  0  0  0]
 [19  1  2  0  0  0  0  0  0  0]
 [15  0  0  0  0  0  0  0  0  0]
 [13  0  1  0  0  1  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0  0]]


In [53]:
#Calculo la precisión del modelo 
from sklearn.metrics import precision_score
precision= precision_score(y_test, y_pred, average="micro", pos_label="yes")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.37373737373737376


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,


In [54]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud= accuracy_score(y_test, y_pred)
print('Exactitud del modelo')
print(exactitud)

Exactitud del modelo
0.37373737373737376


In [55]:
#Calculo la sensibilidad del modelo 
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test, y_pred, average='micro', pos_label="yes")
print('Sensibilidad del modelo')
print(sensibilidad)

Sensibilidad del modelo
0.37373737373737376


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,


## CONJUNTO DE VARIABLES 3

In [56]:
#5Y6
#analizamos caso 1 de correlación entre variable de número de clientes en la tienda respecto al número de estantes en la tienda, el número de refrigeradores y el número de empleados permanentes
Vars_Indep= data4_iqr[['36_credit_default_rate','62_frequency_only_services', '103_number_own_fridges']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

In [57]:
#se define modelo como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [58]:
#Verificamos la función relacionada al modelo 
type(model)

sklearn.linear_model._base.LinearRegression

In [59]:
#ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)

LinearRegression()

In [60]:
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'normalize': 'deprecated',
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['36_credit_default_rate', '62_frequency_only_services',
        '103_number_own_fridges'], dtype=object),
 'n_features_in_': 3,
 'coef_': array([-0.06255288,  0.01020902,  0.00172619]),
 '_residues': 1085.937983316679,
 'rank_': 3,
 'singular_': array([283.96414807,  55.07395916,  36.25516219]),
 'intercept_': 1.4139198844734187}

In [61]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R determinado
model.score(Vars_Indep,Var_Dep)

0.009498351296023055

In [62]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep= data4_iqr[['36_credit_default_rate','62_frequency_only_services', '103_number_own_fridges']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

In [63]:
#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

In [64]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [65]:
#Se escalan todos los datos
escalar= StandardScaler()

In [66]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [67]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [68]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [69]:
#Realizamos una predicción
y_pred= algoritmo.predict(X_test)
y_pred 

array([2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0])

In [70]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[46  0  0  0  0  0  0  0  0]
 [20  0  0  0  0  0  0  0  0]
 [11  0  2  0  0  0  0  0  0]
 [11  0  0  0  0  0  0  0  0]
 [ 5  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0]]


In [71]:
#Calculo la precisión del modelo 
from sklearn.metrics import precision_score
precision= precision_score(y_test, y_pred, average="micro", pos_label="yes")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.48484848484848486


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,


In [72]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud= accuracy_score(y_test, y_pred)
print('Exactitud del modelo')
print(exactitud)

Exactitud del modelo
0.48484848484848486


In [73]:
#Calculo la sensibilidad del modelo 
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test, y_pred, average='micro', pos_label="yes")
print('Sensibilidad del modelo')
print(sensibilidad)

Sensibilidad del modelo
0.48484848484848486


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
